### ISSUE TITLE
the generated parameters.yml for symfony2 is set to use mysql pdo driver instead of postgresql

### ISSUE THREAD

**Issue by allan-simon** [we-bridge/vagrant-ansible-symfony#10]
same for the password/username which is not the one we generate during provisioning

**Comment by cbrunnkvist** [comment]
Aha. I suppose it should be a j2 template rathe than a lineinfile replacement job...

**Comment by cbrunnkvist** [comment]
Speaking of MySQL - I remember talking about adding that role too. I'll fix this issue in the same go.

**Comment by allan-simon** [comment]
yes, the next step would be to use the  composer.json   post-install to generate the parameters.yml from a .dist and env variables
