### ISSUE TITLE
add git in the list of installed package

### ISSUE THREAD

**Issue by allan-simon** [we-bridge/vagrant-ansible-symfony#14]
for some reason, network problem, or  dependencies changing their own dependencies, (both cases already happened)  composer will fail to get  the dependencies from "dist" and will fallback on "git" which is not installed in the vm

**Comment by cbrunnkvist** [comment]
Ohh, I just realized that it has to be available prior to the install step (not that we use composer to install for now, but...this was the background for this ticket). I appended it at the end of the list of plays :-/

I'll update the branch again.

**Comment by cbrunnkvist** [comment]
Fixed. On master.
